spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL8Dialect
        format_sql: true
    show-sql: true
